### ISSUE TITLE
Remove utf folder from common and make necessary changes in build-scripts of Seattle repositories 

### ISSUE THREAD

**Issue by choksi81** [SeattleTestbed/common#21]
`utf` folder is to be removed from `common` repo, and hence, config_initialize and config_build files should include separate `utf` repo for cloning and copying into target directory.

**Comment by aaaaalbert** [comment]
What's the status of this?

**Comment by aaaaalbert** [comment]
Fixed by @choksi81 in SeattleTestbed/utf#54.
